### ISSUE TITLE
Undefined constant Command::SUCCESS

### ISSUE THREAD

**Issue by seasoftjapan** [nanasess/eccube2-fixture-generator#11]
```
$ docker-compose exec -T ec-cube php -ddisplay_errors=1 data/vendor/bin/eccube eccube:fixtures:generate --products=5 --customers=1 --orders=5


Warning: Undefined array key "HTTP_HOST" in /var/www/app/data/config/config.php on line 3

Warning: Undefined array key "HTTP_HOST" in /var/www/app/data/config/config.php on line 4
<br />
<b>Fatal error</b>:  Uncaught Error: Undefined constant Symfony\Component\Console\Command\Command::SUCCESS in /var/www/app/data/vendor/nanasess/eccube2-fixture-generator/src/Command/GenerateDummyDataCommand.php:125
Stack trace:
#0 /var/www/app/data/vendor/symfony/console/Command/Command.php(255): Eccube2\Command\GenerateDummyDataCommand-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/app/data/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/app/data/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Eccube2\Command\GenerateDummyDataCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/app/data/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/app/data/vendor/ec-cube2/cli/bin/eccube(10): Symfony\Component\Console\Application-&gt;run()
#5 /var/www/app/data/vendor/bin/eccube(119): include('/var/www/app/da...')
#6 {main}
  thrown in <b>/var/www/app/data/vendor/nanasess/eccube2-fixture-generator/src/Command/GenerateDummyDataCommand.php</b> on line <b>125</b><br />
```
Symfony\Component\Console\Command\Command::SUCCESS は symfony/console 4以下で定義されていないようです。
https://github.com/symfony/console/blob/4.4/Command/Command.php
https://github.com/nanasess/eccube2-fixture-generator/blob/59546afe58352a486f32ef6b2db8c07169e9b5f9/src/Command/GenerateDummyDataCommand.php#L122-L125
https://github.com/nanasess/eccube2-fixture-generator/blob/59546afe58352a486f32ef6b2db8c07169e9b5f9/composer.json#L5

**Comment by nanasess** [comment]
@seasoftjapan ご指摘ありがとうございます。 修正して 2.0.1 をリリースしました。
https://github.com/nanasess/eccube2-fixture-generator/releases/tag/2.0.1

もし 1.2.x をお使いであれば、こちらも修正しましょうか？

**Comment by seasoftjapan** [comment]
> もし 1.2.x をお使いであれば、こちらも修正しましょうか？

確認したら、2.0.0 でした。
2.0.1 を反映し、エラー解消されました。

**Comment by nanasess** [comment]
#12 で対応しましたのでクローズします
